In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, VotingRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score
import numpy as np

In [2]:
new_data = pd.read_csv('cleaned_data_telecom.csv')

In [3]:
categorical_columns = [
    'gender', 'partner', 'dependents', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup', 'device_protection',
    'tech_support', 'streaming_t_v', 'streaming_movies', 'contract',
    'paperless_billing', 'payment_method', 'churn'
]

In [4]:
telecom_data_encoded = pd.get_dummies(new_data, columns=categorical_columns, drop_first=True)

In [5]:
telecom_data_encoded

,senior_citizen,tenure,monthly_charges,total_charges,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,...,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn_Yes
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,0,24,84.80,1990.50,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7006,0,72,103.20,7362.90,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7007,0,11,29.60,346.45,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7008,1,4,74.40,306.60,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7009,0,66,105.65,6844.50,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [6]:
numerical_columns = ['tenure', 'monthly_charges', 'total_charges']

In [7]:
scaler = StandardScaler()

In [10]:
telecom_data_encoded[numerical_columns] = scaler.fit_transform(telecom_data_encoded[numerical_columns])

In [14]:
telecom_data_encoded

,senior_citizen,tenure,monthly_charges,total_charges,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,...,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn_Yes
0,0,-1.285566,-1.165523,-0.997284,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,0.060346,-0.264071,-0.176848,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,-1.244781,-0.367189,-0.962740,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,0.508983,-0.751387,-0.198355,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,-1.244781,0.193308,-0.943549,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,0,-0.347506,0.662329,-0.132289,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7006,0,1.610184,1.274384,2.237896,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7007,0,-0.877714,-1.173839,-0.857607,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7008,1,-1.163210,0.316384,-0.875188,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7009,0,1.365473,1.355881,2.009189,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [19]:
X = telecom_data_encoded.drop('churn_Yes', axis=1)
y = telecom_data_encoded['churn_Yes']

In [21]:
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42)


svm_clf = SVC(kernel='rbf', class_weight='balanced', probability=True, random_state=42)
svm_clf.fit(X_train, y_train)


y_pred_val = svm_clf.predict(X_val)
print(classification_report(y_val, y_pred_val))
print(f"SVM AUC-ROC on Validation Set: {roc_auc_score(y_val, y_pred_val):.4f}")

              precision    recall  f1-score   support

       False       0.91      0.76      0.83      1014
        True       0.56      0.81      0.66       388

    accuracy                           0.77      1402
   macro avg       0.73      0.78      0.74      1402
weighted avg       0.81      0.77      0.78      1402

SVM AUC-ROC on Validation Set: 0.7816