In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor, VotingRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
import re
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score
import numpy as np

# THIS IS A NOTEBOOK WHERE I TRY DIFFERENT MODELS ON THE DATA THAT I DON'T REMOVE THE DUPLICATES OF

In [2]:
new_data = pd.read_csv('test_cleaned.csv')

In [3]:
categorical_columns = [
    'gender', 'partner', 'dependents', 'phone_service', 'multiple_lines',
    'internet_service', 'online_security', 'online_backup', 'device_protection',
    'tech_support', 'streaming_t_v', 'streaming_movies', 'contract',
    'paperless_billing', 'payment_method', 'churn'
]

In [4]:
telecom_data_encoded = pd.get_dummies(new_data, columns=categorical_columns, drop_first=True)

In [5]:
telecom_data_encoded

,senior_citizen,tenure,monthly_charges,total_charges,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,...,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn_Yes
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,24,84.80,1990.50,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7028,0,72,103.20,7362.90,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7029,0,11,29.60,346.45,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7030,1,4,74.40,306.60,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7031,0,66,105.65,6844.50,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [6]:
numerical_columns = ['tenure', 'monthly_charges', 'total_charges']

In [7]:
scaler = StandardScaler()

In [8]:
telecom_data_encoded[numerical_columns] = scaler.fit_transform(telecom_data_encoded[numerical_columns])

In [9]:
telecom_data_encoded

,senior_citizen,tenure,monthly_charges,total_charges,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,...,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn_Yes
0,0,-1.280248,-1.161694,-0.994194,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,0.064303,-0.260878,-0.173740,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,-1.239504,-0.363923,-0.959649,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,0.512486,-0.747850,-0.195248,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,-1.239504,0.196178,-0.940457,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7027,0,-0.343137,0.664868,-0.129180,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7028,0,1.612573,1.276493,2.241056,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7029,0,-0.872808,-1.170004,-0.854514,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7030,1,-1.158016,0.319168,-0.872095,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7031,0,1.368109,1.357932,2.012344,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False

In [21]:
X = telecom_data_encoded.drop('churn_Yes', axis=1)
y = telecom_data_encoded['churn_Yes']
X_train_val, X_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.25, random_state=42)

In [11]:


svm_clf = SVC(kernel='rbf', class_weight='balanced', probability=True, random_state=42)
svm_clf.fit(X_train, y_train)


y_pred_val = svm_clf.predict(X_val)
print(classification_report(y_val, y_pred_val))
print(f"SVM AUC-ROC on Validation Set: {roc_auc_score(y_val, y_pred_val):.4f}")

              precision    recall  f1-score   support

       False       0.91      0.73      0.81      1020
        True       0.53      0.81      0.64       387

    accuracy                           0.75      1407
   macro avg       0.72      0.77      0.73      1407
weighted avg       0.81      0.75      0.76      1407

SVM AUC-ROC on Validation Set: 0.7691

In [23]:

rf_clf = RandomForestClassifier(class_weight='balanced', random_state=42)

# Train the model on training data
rf_clf.fit(X_train, y_train)

# Predict on the validation set
y_pred_val = rf_clf.predict(X_val)

# Print classification report and AUC-ROC score
print(classification_report(y_val, y_pred_val))

              precision    recall  f1-score   support

       False       0.82      0.91      0.86      1020
        True       0.67      0.48      0.56       387

    accuracy                           0.79      1407
   macro avg       0.74      0.69      0.71      1407
weighted avg       0.78      0.79      0.78      1407

In [30]:
from xgboost import XGBClassifier

# Initialize XGBoost model
xgb_clf = XGBClassifier(scale_pos_weight=len(y_train[y_train == 0]) / len(y_train[y_train == 1]), random_state=42)

# Train the model on training data
xgb_clf.fit(X_train, y_train)

# Predict on the validation set
y_pred_val = xgb_clf.predict(X_val)

# Print classification report and AUC-ROC score
print(classification_report(y_val, y_pred_val))

              precision    recall  f1-score   support

       False       0.86      0.79      0.82      1020
        True       0.55      0.67      0.60       387

    accuracy                           0.76      1407
   macro avg       0.70      0.73      0.71      1407
weighted avg       0.78      0.76      0.76      1407

In [38]:
from sklearn.linear_model import LogisticRegression

# Initialize Logistic Regression model
lr_clf = LogisticRegression(class_weight='balanced', random_state=42)

# Train the model on training data
lr_clf.fit(X_train, y_train)

# Predict on the validation set
y_pred_val = lr_clf.predict(X_val)

# Print classification report and AUC-ROC score
print(classification_report(y_val, y_pred_val))

              precision    recall  f1-score   support

       False       0.93      0.71      0.80      1020
        True       0.52      0.85      0.65       387

    accuracy                           0.75      1407
   macro avg       0.72      0.78      0.72      1407
weighted avg       0.82      0.75      0.76      1407

Poudel, S. S., Pokharel, S., & Timilsina, M. (2024). Explaining customer churn prediction in telecom industry using tabular machine learning models. Machine Learning With Applications, 17, 100567. https://doi.org/10.1016/j.mlwa.2024.100567

Ahmed, A. A., & Maheswari, D. (2017). Churn prediction on huge telecom data using hybrid firefly based classification. Egyptian Informatics Journal, 18(3), 215–220. https://doi.org/10.1016/j.eij.2017.02.002

Jain, H., Khunteta, A., & Srivastava, S. (2020). Churn Prediction in Telecommunication using Logistic Regression and Logit Boost. Procedia Computer Science, 167, 101–112. https://doi.org/10.1016/j.procs.2020.03.187