In [1]:
# Imports
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix
from imblearn.combine import SMOTEENN

# Load Dataset
df = pd.read_csv("cleaned_data_telecom.csv")

# Preprocess Data
df = pd.get_dummies(df, drop_first=True)

# Split Data
X = df.drop("churn_Yes", axis=1)
y = df["churn_Yes"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Apply SMOTE-ENN to balance the dataset
smote_enn = SMOTEENN()
X_res, y_res = smote_enn.fit_resample(X_train, y_train)

# Train Decision Tree Classifier
dt = DecisionTreeClassifier(random_state=42)
dt.fit(X_res, y_res)
y_pred_dt = dt.predict(X_test)
print("Decision Tree Performance:")
print(classification_report(y_test, y_pred_dt))

# Train Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_res, y_res)
y_pred_rf = rf.predict(X_test)
print("Random Forest Performance:")
print(classification_report(y_test, y_pred_rf))

Decision Tree Performance:
              precision    recall  f1-score   support

       False       0.90      0.74      0.81      1081
        True       0.44      0.71      0.55       321

    accuracy                           0.73      1402
   macro avg       0.67      0.72      0.68      1402
weighted avg       0.79      0.73      0.75      1402

Random Forest Performance:
              precision    recall  f1-score   support

       False       0.91      0.75      0.82      1081
        True       0.47      0.76      0.58       321

    accuracy                           0.75      1402
   macro avg       0.69      0.75      0.70      1402
weighted avg       0.81      0.75      0.77      1402

In [3]:
df

,senior_citizen,tenure,monthly_charges,total_charges,gender_Male,partner_Yes,dependents_Yes,phone_service_Yes,multiple_lines_No phone service,multiple_lines_Yes,...,streaming_t_v_Yes,streaming_movies_No internet service,streaming_movies_Yes,contract_One year,contract_Two year,paperless_billing_Yes,payment_method_Credit card (automatic),payment_method_Electronic check,payment_method_Mailed check,churn_Yes
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,True,False,False,False,False,True,False
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,True,False,False,True,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,True,False,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,True,False,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7005,0,24,84.80,1990.50,True,True,True,True,False,True,...,True,False,True,True,False,True,False,False,True,False
7006,0,72,103.20,7362.90,False,True,True,True,False,True,...,True,False,True,True,False,True,True,False,False,False
7007,0,11,29.60,346.45,False,True,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
7008,1,4,74.40,306.60,True,True,False,True,False,True,...,False,False,False,False,False,True,False,False,True,True
7009,0,66,105.65,6844.50,True,False,False,True,False,False,...,True,False,True,False,True,True,False,False,False,False